
import com.mysql.jdbc.exceptions.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RDHXT
 */
public class IssueBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    
    public IssueBook() {
        super("Issue Book");
        initComponents();
        conn=javaConnect.ConnectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        publisherField = new javax.swing.JTextField();
        pagesField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        bookField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        editionField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        authorField = new javax.swing.JTextField();
        idField = new javax.swing.JTextField();
        stunameField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        mobileField = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        occupationField = new javax.swing.JTextField();
        genderField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        issuebutton = new javax.swing.JButton();
        Home_Button = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        publisherField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherFieldActionPerformed(evt);
            }
        });
        jPanel1.add(publisherField);
        publisherField.setBounds(280, 310, 150, 30);
        jPanel1.add(pagesField);
        pagesField.setBounds(280, 390, 150, 30);

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton);
        searchButton.setBounds(329, 440, 100, 29);
        jPanel1.add(bookField);
        bookField.setBounds(280, 140, 150, 30);

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nameField);
        nameField.setBounds(280, 190, 150, 30);

        editionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editionFieldActionPerformed(evt);
            }
        });
        jPanel1.add(editionField);
        editionField.setBounds(280, 230, 150, 30);
        jPanel1.add(priceField);
        priceField.setBounds(280, 350, 150, 30);

        authorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorFieldActionPerformed(evt);
            }
        });
        jPanel1.add(authorField);
        authorField.setBounds(280, 270, 150, 30);

        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });
        jPanel1.add(idField);
        idField.setBounds(790, 140, 151, 30);

        stunameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stunameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(stunameField);
        stunameField.setBounds(790, 180, 150, 30);

        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });
        jPanel1.add(addressField);
        addressField.setBounds(790, 380, 150, 30);

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailField);
        emailField.setBounds(790, 260, 150, 30);

        mobileField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileFieldActionPerformed(evt);
            }
        });
        jPanel1.add(mobileField);
        mobileField.setBounds(790, 220, 151, 30);

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search.png"))); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(839, 470, 110, 29);
        jPanel1.add(occupationField);
        occupationField.setBounds(790, 300, 150, 30);
        jPanel1.add(genderField);
        genderField.setBounds(790, 340, 150, 30);

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);
        backButton.setBounds(290, 500, 100, 29);

        issuebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add.png"))); // NOI18N
        issuebutton.setText("Issue");
        issuebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(issuebutton);
        issuebutton.setBounds(470, 500, 100, 29);

        Home_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeIcon.jpg"))); // NOI18N
        Home_Button.setText("Home");
        Home_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Home_Button);
        Home_Button.setBounds(640, 500, 100, 29);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(790, 420, 150, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/issueImage.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 1000, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void publisherFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisherFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publisherFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String sq1= "select * from Student where Reader_ID=?";
        try{
            pst=conn.prepareStatement(sq1);
            pst.setString(1,idField.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String s1=rs.getString("Reader_Name");
                stunameField.setText(s1);
                String s2=rs.getString("Mobile");
                mobileField.setText(s2);
                String s3=rs.getString("Email");
                emailField.setText(s3);
                String s4=rs.getString("Occupation");
                occupationField.setText(s4);
                String s5=rs.getString("Gender");
                genderField.setText(s5);
                String s6=rs.getString("Address");
                addressField.setText(s6);
                rs.close();
                pst.close();
            }
                else
                {
                    JOptionPane.showMessageDialog(null,"Invalid Reader ID");      
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_searchActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        setVisible(false);
        AvailableBooks w=new AvailableBooks();
        w.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String sq1= "select * from Book where Book_ID=?";
        try{
            pst=conn.prepareStatement(sq1);
            pst.setString(1,bookField.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String s1=rs.getString("Book_Name");
                nameField.setText(s1);
                String s2=rs.getString("Edition");
                editionField.setText(s2);
                String s3=rs.getString("Author");
                authorField.setText(s3);
                String s4=rs.getString("Publisher");
                publisherField.setText(s4);
                String s5=rs.getString("Price");
                priceField.setText(s5);
                String s6=rs.getString("Pages");
                pagesField.setText(s6);
                rs.close();
                pst.close();
            }
                else
                {
                    JOptionPane.showMessageDialog(null,"Invalid Book ID");      
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void issuebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuebuttonActionPerformed
       String sq1="insert into Issue(Book_ID,Book_Name,Edition,Author,Publisher,Price,Pages,Reader_ID,Reader_Name,Mobile,Email,Occupation,Gender,Address,DOI) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
       int copy=0;
       try{
           pst=conn.prepareStatement(sq1);
           pst.setString(1,bookField.getText());
           pst.setString(2,nameField.getText());
           pst.setString(3,editionField.getText());
           pst.setString(4,authorField.getText());
           pst.setString(5,publisherField.getText());
           pst.setString(6,priceField.getText());
           pst.setString(7,pagesField.getText());
           pst.setString(8,idField.getText());
           pst.setString(9,stunameField.getText());
           pst.setString(10,mobileField.getText());
           pst.setString(11,emailField.getText());
           pst.setString(12,occupationField.getText());
           pst.setString(13,genderField.getText());
           pst.setString(14,addressField.getText());
           pst.setString(15,((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
           pst.execute();
          // JOptionPane.showMessageDialog(null,"Book Issued Successfully!");
       }catch(com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException ex){
           JOptionPane.showMessageDialog(null,"The reader has already taken a book!");
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
       
       String sq2= "select * from Book where Book_ID=?";
        try{
            pst=conn.prepareStatement(sq2);
            pst.setString(1,bookField.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                copy=Integer.parseInt(rs.getString("Copies"));
                //System.out.println(copy);
                rs.close();
                pst.close();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }

       String sq3="update book set Copies = ? where Book_ID ="+bookField.getText();
       try{
           if(copy>=1)
           {
               copy--;
               pst=conn.prepareStatement(sq3);
               pst.setInt(1,copy);
               pst.executeUpdate();
               JOptionPane.showMessageDialog(null,"Book Issued Successfully!");
           }
           else
           {
               JOptionPane.showMessageDialog(null,"The Book is Out of Stock!");
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
    }//GEN-LAST:event_issuebuttonActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void stunameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stunameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stunameFieldActionPerformed

    private void editionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editionFieldActionPerformed

    private void authorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorFieldActionPerformed

    private void mobileFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileFieldActionPerformed

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFieldActionPerformed

    private void Home_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_ButtonActionPerformed
       setVisible(false);
       Welcome w= new Welcome();
       w.setVisible(true);
    }//GEN-LAST:event_Home_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home_Button;
    private javax.swing.JTextField addressField;
    private javax.swing.JTextField authorField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField bookField;
    private javax.swing.JTextField editionField;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField genderField;
    private javax.swing.JTextField idField;
    private javax.swing.JButton issuebutton;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mobileField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField occupationField;
    private javax.swing.JTextField pagesField;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextField publisherField;
    private javax.swing.JButton search;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField stunameField;
    // End of variables declaration//GEN-END:variables
}
