
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class NewBook extends javax.swing.JFrame {

    /**
     * Creates new form NewBook
     */
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    
    public NewBook() {
        super("New Book");
        initComponents();
        conn=javaConnect.ConnectDb();
        Random();
    }
    
    public void Random()
    {
        Random rd=new Random();
        BookID_TextField.setText(""+rd.nextInt(1000+1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Edition_ComboBox = new javax.swing.JComboBox<>();
        Publisher_TextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        BookID_TextField = new javax.swing.JTextField();
        Name_TextField = new javax.swing.JTextField();
        Pages_TextField = new javax.swing.JTextField();
        Price_TextField = new javax.swing.JTextField();
        Author_TextField = new javax.swing.JTextField();
        copiesField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(130, 550, 100, 30);

        Edition_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th", "9th", "10th", "11th", "12th" }));
        jPanel1.add(Edition_ComboBox);
        Edition_ComboBox.setBounds(200, 240, 205, 30);
        jPanel1.add(Publisher_TextField);
        Publisher_TextField.setBounds(200, 340, 205, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(340, 550, 100, 30);

        BookID_TextField.setEditable(false);
        BookID_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookID_TextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(BookID_TextField);
        BookID_TextField.setBounds(200, 130, 205, 30);
        jPanel1.add(Name_TextField);
        Name_TextField.setBounds(200, 190, 205, 30);
        jPanel1.add(Pages_TextField);
        Pages_TextField.setBounds(200, 440, 205, 30);

        Price_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Price_TextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(Price_TextField);
        Price_TextField.setBounds(200, 390, 205, 30);
        jPanel1.add(Author_TextField);
        Author_TextField.setBounds(200, 290, 205, 30);

        copiesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiesFieldActionPerformed(evt);
            }
        });
        jPanel1.add(copiesField);
        copiesField.setBounds(200, 500, 210, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewBook.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        Welcome we=new Welcome();
        we.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String sql="Insert into book (Book_ID,Book_Name,Edition,Author,Publisher,Price,Pages,Copies) values(?,?,?,?,?,?,?,?)";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1, BookID_TextField.getText());
            pst.setString(2, Name_TextField.getText());
            pst.setString(3, (String) Edition_ComboBox.getSelectedItem());
            pst.setString(4, Author_TextField.getText());
            pst.setString(5, Publisher_TextField.getText());
            pst.setString(6, Price_TextField.getText());
            pst.setString(7, Pages_TextField.getText());
            pst.setString(8, copiesField.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"New Book Added!");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BookID_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookID_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookID_TextFieldActionPerformed

    private void Price_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Price_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Price_TextFieldActionPerformed

    private void copiesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copiesFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Author_TextField;
    private javax.swing.JTextField BookID_TextField;
    private javax.swing.JComboBox<String> Edition_ComboBox;
    private javax.swing.JTextField Name_TextField;
    private javax.swing.JTextField Pages_TextField;
    private javax.swing.JTextField Price_TextField;
    private javax.swing.JTextField Publisher_TextField;
    private javax.swing.JTextField copiesField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
