
import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class ReturnBook extends javax.swing.JFrame {
    
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form ReturnBook
     */
    public ReturnBook() {
        super("Return Book");
        initComponents();
        conn=javaConnect.ConnectDb();
    }
     public void Delete(){
         String sql="delete from Issue where Reader_ID=?";
         try{
             pst=conn.prepareStatement(sql);
            pst.setString(1,idField.getText());
            pst.execute();
         }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
         }
     }
     
     public void returnUpdate(){
         String sql="insert into returnbook(Reader_ID,Reader_Name,Mobile,Email,Occupation,Gender,Address,Book_ID,Book_Name,Edition,Author,Publisher,Price,Pages,DOI,DOR)values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
         int copy=0; 
         int rating1=Integer.parseInt(ratingField.getText());
         int rating2=0;
         try{
           pst=conn.prepareStatement(sql);
           pst.setString(1,idField.getText());
           pst.setString(2,stunameField.getText());
           pst.setString(3,mobileField.getText());
           pst.setString(4,emailField.getText());
           pst.setString(5,occupationField.getText());
           pst.setString(6,genderField.getText());
           pst.setString(7,addressField.getText());
           pst.setString(8,bookField.getText());
           pst.setString(9,nameField.getText());
           pst.setString(10,editionField.getText());
           pst.setString(11,authorField.getText());
           pst.setString(12,publisherField.getText());
           pst.setString(13,priceField.getText());
           pst.setString(14,pagesField.getText());
           pst.setString(15,datefield.getText());
           pst.setString(16,((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
           pst.execute();
           JOptionPane.showMessageDialog(null,"Book Returned!");
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
           
       String sq2= "select * from Book where Book_ID=?";
        try{
            pst=conn.prepareStatement(sq2);
            pst.setString(1,bookField.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                copy=Integer.parseInt(rs.getString("Copies"));
                rating2=Integer.parseInt(rs.getString("Rating"));
                //System.out.println(copy);
                rs.close();
                pst.close();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                
            }
        }

       String sq3="update book set Copies = ? where Book_ID ="+bookField.getText();
       try{
           if(copy>=0)
           {
               copy++;
               pst=conn.prepareStatement(sq3);
               pst.setInt(1,copy);
               pst.executeUpdate();
              // JOptionPane.showMessageDialog(null,"Database Updated Successfully!");
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
       
       String sq4="update book set Rating = ? where Book_ID ="+bookField.getText();
       try{
               int rating=0;
               if(rating2==0)
                   rating=rating1;
               else
                    rating=(rating1+rating2)/2;
               pst=conn.prepareStatement(sq4);
               pst.setInt(1,rating);
               pst.executeUpdate();
               //JOptionPane.showMessageDialog(null,"Database Updated Successfully!");
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        priceField = new javax.swing.JTextField();
        editionField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        publisherField = new javax.swing.JTextField();
        authorField = new javax.swing.JTextField();
        bookField = new javax.swing.JTextField();
        stunameField = new javax.swing.JTextField();
        mobileField = new javax.swing.JTextField();
        idField = new javax.swing.JTextField();
        pagesField = new javax.swing.JTextField();
        occupationField = new javax.swing.JTextField();
        genderField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        datefield = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        returnbutton = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        ratingField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(priceField);
        priceField.setBounds(680, 380, 193, 30);

        editionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editionFieldActionPerformed(evt);
            }
        });
        jPanel1.add(editionField);
        editionField.setBounds(680, 230, 193, 30);

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailField);
        emailField.setBounds(210, 270, 205, 30);

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nameField);
        nameField.setBounds(680, 180, 193, 30);
        jPanel1.add(addressField);
        addressField.setBounds(210, 440, 205, 30);

        publisherField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherFieldActionPerformed(evt);
            }
        });
        jPanel1.add(publisherField);
        publisherField.setBounds(680, 330, 193, 30);

        authorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorFieldActionPerformed(evt);
            }
        });
        jPanel1.add(authorField);
        authorField.setBounds(680, 290, 193, 30);
        jPanel1.add(bookField);
        bookField.setBounds(680, 130, 193, 30);
        jPanel1.add(stunameField);
        stunameField.setBounds(210, 170, 205, 30);
        jPanel1.add(mobileField);
        mobileField.setBounds(210, 220, 205, 30);
        jPanel1.add(idField);
        idField.setBounds(210, 120, 205, 30);
        jPanel1.add(pagesField);
        pagesField.setBounds(680, 430, 193, 30);
        jPanel1.add(occupationField);
        occupationField.setBounds(210, 320, 205, 30);
        jPanel1.add(genderField);
        genderField.setBounds(210, 380, 205, 30);

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton);
        searchButton.setBounds(300, 500, 110, 29);
        jPanel1.add(datefield);
        datefield.setBounds(680, 480, 193, 30);

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);
        backButton.setBounds(780, 610, 90, 30);

        returnbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Retrieve.jpg"))); // NOI18N
        returnbutton.setText("Return");
        returnbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(returnbutton);
        returnbutton.setBounds(120, 500, 89, 29);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(680, 530, 190, 30);
        jPanel1.add(ratingField);
        ratingField.setBounds(680, 570, 190, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/returnBook.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, -10, 940, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbuttonActionPerformed
        Delete();
        returnUpdate();
    }//GEN-LAST:event_returnbuttonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        setVisible(false);
        Welcome w=new Welcome();
        w.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String sql="select * from Issue Where Reader_ID=?";

        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1,idField.getText());
            rs=pst.executeQuery();

            if(rs.next()){
                String s1=rs.getString("Reader_Name");
                stunameField.setText(s1);

                String s2=rs.getString("Mobile");
                mobileField.setText(s2);

                String s3=rs.getString("Email");
                emailField.setText(s3);

                String s4=rs.getString("Occupation");
                occupationField.setText(s4);

                String s5=rs.getString("Gender");
                genderField.setText(s5);

                String s6=rs.getString("Address");
                addressField.setText(s6);

                String s7=rs.getString("Book_ID");
                bookField.setText(s7);

                String s8=rs.getString("Book_Name");
                nameField.setText(s8);

                String s9=rs.getString("Edition");
                editionField.setText(s9);

                String s10=rs.getString("Author");
                authorField.setText(s10);

                String s11=rs.getString("Publisher");
                publisherField.setText(s11);

                String s12=rs.getString("Price");
                priceField.setText(s12);

                String s13=rs.getString("Pages");
                pagesField.setText(s13);

                String s14=rs.getString("DOI");
                datefield.setText(s14);

                rs.close();
                pst.close();
            }

            else{
                JOptionPane.showMessageDialog(null,"Book is not issued with this Student ID");
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){

            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void publisherFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisherFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publisherFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void authorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorFieldActionPerformed

    private void editionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editionFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JTextField authorField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField bookField;
    private javax.swing.JTextField datefield;
    private javax.swing.JTextField editionField;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField genderField;
    private javax.swing.JTextField idField;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mobileField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField occupationField;
    private javax.swing.JTextField pagesField;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextField publisherField;
    private javax.swing.JTextField ratingField;
    private javax.swing.JButton returnbutton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField stunameField;
    // End of variables declaration//GEN-END:variables
}
